package org.egel;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import java.io.InputStream;

/**
 * Created by campitos on 23/02/17.
 */
@Entity
public class Binario1 {

    @Id
    @GeneratedValue
    Long id;

    String nombre;

    @Lob
    byte[] archivo;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public byte[] getArchivo() {
        return archivo;
    }

    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }

    public Binario1(String nombre, byte[] archivo) {
        this.nombre = nombre;
        this.archivo = archivo;
    }

    public Binario1() {
    }
}